function set_publication_graphics
% Make exported figures independent of the interactive MATLAB color theme.
set(groot, ...
    'defaultFigureColor','w', ...
    'defaultAxesColor','w', ...
    'defaultAxesXColor','k', ...
    'defaultAxesYColor','k', ...
    'defaultAxesZColor','k', ...
    'defaultAxesGridColor',[0.75 0.75 0.75], ...
    'defaultTextColor','k', ...
    'defaultLegendColor','w', ...
    'defaultLegendTextColor','k', ...
    'defaultLegendEdgeColor',[0.35 0.35 0.35]);
end
